version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  browser-tools: circleci/browser-tools@1.1
  bullet_train_testing: gazayas/bullet_train_testing@dev:30d314f312e1e4537a3b8d654ce0b29094240f69
aliases:
  - &restore_bundler_cache
      name: Restore Bundler cache
      keys:
        - gem-cache-v1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - gem-cache-v1-{{ .Branch }}-
        - gem-cache-v1-
  - &restore_yarn_cache
      name: Restore Yarn cache
      keys:
        - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
        - yarn-packages-v1-{{ .Branch }}-
        - yarn-packages-
  - &save_bundle_cache
      name: Save Bundle cache
      key: gem-cache-v1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle
  - &save_yarn_cache
      name: Save Yarn cache
      key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      paths:
        - node_modules
  - &ruby_node_browsers_docker_image
      - image: cimg/ruby:3.1.2-browsers
        environment:
          PGHOST: localhost
          PGUSER: untitled_application
          RAILS_ENV: test
  - &postgres_docker_image
      - image: circleci/postgres
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: untitled_application_test
          POSTGRES_USER: untitled_application
  - &wait_for_docker
      # We run this because the DB might not be available for a while due to a race condition.
      run: dockerize -wait tcp://localhost:5432 -timeout 1m
jobs:
  'Local Minitest':
    docker:
      - <<: *ruby_node_browsers_docker_image
      - <<: *postgres_docker_image
      - image: circleci/redis
    executor: ruby/default
    steps:
      - browser-tools/install-browser-tools
      - checkout

      # Install dependencies
      - run: "bundle install"
      - run: "bundle clean --force"
      - run: "yarn install"
      - *wait_for_docker
      - run:
          name: Run unit tests
          command: bundle exec rails test

  'Local Standard Ruby':
    docker:
      - <<: *ruby_node_browsers_docker_image
    steps:
      - checkout

      # TODO Figure out how to make these work for `tmp/starter`
      # # Restore dependency caches
      # - restore_cache: *restore_bundler_cache
      # - restore_cache: *restore_yarn_cache

      # Install dependencies
      - ruby/bundle-install
      - run: bundle clean --force
      - run: yarn install

      # # Save dependency caches
      # # We only do this as part of this job, because it's time consuming and we don't want it to slow down test runners.
      # - save_cache: *save_bundle_cache
      # - save_cache: *save_yarn_cache

      - bullet_train_testing/standard_ruby

  'Starter Repo Minitest':
    docker:
      - <<: *ruby_node_browsers_docker_image
      - <<: *postgres_docker_image
      - image: circleci/redis
    executor: ruby/default
    parallelism: 16
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - bullet_train_testing/starter_repo_minitest:
          packageName: bullet_train-base
          # If you don't want to use Knapsack Pro, remove these two variables
          knapsackPro: true
          parallelism: 16

      # If you want to gather test results in CircleCI when not running tests in parallel,
      # include `minitest-ci` in your Gemfile and uncomment the following step.
      # You can access the test results via the "Tests" tab within each build in CircleCI.
      #
      # - store_test_results:
      #     path: test/reports

  'Starter Repo Minitest for Super Scaffolding':
    docker:
      - <<: *ruby_node_browsers_docker_image
      - <<: *postgres_docker_image
      - image: circleci/redis
    executor: ruby/default
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run: "git clone https://github.com/bullet-train-co/bullet_train.git tmp/starter"

      - run:
          name: Link starter repository to the Ruby gem being tested.
          command: "grep -v 'gem \"bullet_train\"' tmp/starter/Gemfile > tmp/starter/Gemfile.tmp && mv tmp/starter/Gemfile.tmp tmp/starter/Gemfile && echo 'gem \"bullet_train\", path: \"../..\"' >> tmp/starter/Gemfile"

      # TODO Figure out how to make these work for `tmp/starter`
      # # Restore dependency caches
      # - restore_cache: *restore_bundler_cache
      # - restore_cache: *restore_yarn_cache

      # Install dependencies
      - run: "cd tmp/starter && bundle install"
      - run: "cd tmp/starter && bundle clean --force"
      - run: "cd tmp/starter && bundle exec rake bt:link"
      - run: "cd tmp/starter && yarn install"
      - run: "cd tmp/starter && yarn build"
      - run: "cd tmp/starter && yarn build:css"

      - *wait_for_docker

      - run: "cd tmp/starter && bundle add spring"
      - run:
          name: 'Setup Super Scaffolding System Test'
          command: "cd tmp/starter && bundle exec test/bin/setup-super-scaffolding-system-test"
      - run:
          name: 'Run Super Scaffolding Test'
          command: "cd tmp/starter && bundle exec rails test test/system/super_scaffolding_test.rb"

workflows:
  version: 2
  build:
    jobs:
      - 'Local Minitest'
      - 'Local Standard Ruby'
      - 'Starter Repo Minitest'
      - 'Starter Repo Minitest for Super Scaffolding'
